### ISSUE TITLE
Box case : demo error 

### ISSUE THREAD

**Issue by Khalife** [dmishin/tsp-solver#1]
I am reporting an error in the tsp.py file used for demo l39 (I am using Python 2.7.10).
xy = np.random.rand((2,N)) should be replaced by xy = np.random.rand(2,N)

**Comment by dmishin** [comment]
Oops. Fixed. Yeah, it only took 2 years...

I forgot to provide email to github, and did not get a notification about this issue. Thanks a lot for the report.
