### ISSUE TITLE
Path becomes shorter when endpoints are set.

### ISSUE THREAD

**Issue by JoeBethke** [dmishin/tsp-solver#8]
My distance matrix: 
[https://pastebin.com/JaBjcdXM](url)

My code:
```
from tsp_solver.greedy import solve_tsp
import csv
with open("matrix.csv") as f:
    r = csv.reader(f, delimiter=',')
    matrix = [[float(i) for i in row] for row in r]

tsp = solve_tsp(matrix, optim_steps=1000, endpoints=None)
d = sum([matrix[tsp[idx]][tsp[idx + 1]] for idx in range(len(tsp) - 1)])

tsp2 = solve_tsp(matrix, optim_steps=1000, endpoints=(5,6))
d2 = sum([matrix[tsp2[idx]][tsp2[idx + 1]] for idx in range(len(tsp2) - 1)])
```

In this instance, I have used solve_tsp twice for the same matrix. In the first case, I have left the endpoints as None, allowing the algorithm to produce it's own path, unconstrained. The outcome for this path (tsp) is:
`[5, 0, 1, 2, 7, 3, 6, 4, 8]
`  and the total distance (d) for this path is:  `77575.488`.
In the second case, I specified endpoints (5, 6) and got a better path: `[5, 0, 1, 2, 7, 3, 8, 4, 6]` with a total distance (d2): `70789.007`.

I'm not sure what is causing this, in your readme you mention that setting the endpoints should increase the length of the path, but that doesn't seem to be the case here. I also got the same results using the numpy version as well.

**Comment by dmishin** [comment]
Sorry for the late comment.

I think, this is not caused by a mistake. The algorithm is sub-optimal, so it is not guaranteed to find the shortest solution. It only finds a reasonably short one.

In most cases, defining endpoints would give a worser solution, but with some luck you could find a better solution. You just found such case.
